# Generated by Django 5.2.3 on 2025-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_picture', models.ImageField(blank=True, null=True, upload_to='event_pictures/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_theme', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
