# Generated by Django 5.2.3 on 2025-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('d_o_b', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('jersey_size', models.CharField(max_length=10)),
                ('shoe_size', models.CharField(max_length=10)),
                ('passport_picture', models.ImageField(upload_to='passport_pictures/')),
                ('full_picture', models.ImageField(upload_to='full_pictures/')),
            ],
        ),
    ]
